framework:
    messenger:
        failure_transport: failed
        transports:

            # MESSENGER TRANSPORT : async
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

            # MESSENGER TRANSPORT : scraper
            scraper:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

            # MESSENGER TRANSPORT : scraper_completed
            scraper_completed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

            # OTHER MESSENGER TRANSPORTS
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # App Async Transports
            App\Message\AppEmailMessage: async
            App\Message\ProccessWebScrapingRequestMessage: scraper
            App\Message\HandleWebScrapingRequestAfterCompletedMessage: scraper_completed

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
