# Local Environment Starter
workers:
  # Start MySQL Server
  mysql:
    cmd: [ 'mysqld' ]

  # Watch NPM
  npm_watch:
    cmd: [ 'npm', 'run', 'watch' ]

  # Start Firebase Emulator
  firebase_emulators:
    cmd: [ 'cd', 'firebase', '&&','firebase', 'emulators:start', '--only', 'functions' ]

  # Start Async Workers
  messenger_consume_async:
    cmd: [ 'symfony', 'console', 'messenger:consume', 'async' ]
    watch: [ 'config/packages/messenger.yaml', 'src/Message', 'src/MessageHandler', 'src/CronTask', 'src/RemoteEvent', 'src/WebHook' ]
  messenger_consume_scheduler_default:
    cmd: [ 'symfony', 'console', 'messenger:consume', 'scheduler_default' ]
    watch: [ 'config/packages/messenger.yaml', 'src/Message', 'src/MessageHandler', 'src/CronTask', 'src/RemoteEvent', 'src/WebHook' ]
  messenger_consume_scraper:
    cmd: [ 'symfony', 'console', 'messenger:consume', 'scraper' ]
    watch: [ 'config/packages/messenger.yaml', 'src/Message', 'src/MessageHandler', 'src/CronTask', 'src/RemoteEvent', 'src/WebHook' ]
  messenger_consume_scraper_completed:
    cmd: [ 'symfony', 'console', 'messenger:consume', 'scraper_completed' ]
    watch: [ 'config/packages/messenger.yaml', 'src/Message', 'src/MessageHandler', 'src/CronTask', 'src/RemoteEvent', 'src/WebHook' ]
