security:
  access_control:
    - { path: ^/admin, roles: ROLE_USER, requires_channel: '%env(REQUIRED_REQUEST_SCHEME)%' }
    - { path: ^/, roles: PUBLIC_ACCESS, requires_channel: '%env(REQUIRED_REQUEST_SCHEME)%' }